#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
#include "images/square.h"
#include "images/start.h"
#include "images/win.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state{
  START,
  START_GAME,
  PLAY,
  WIN,
};

Player player = {15, 35, 10, 10, 0};
Enemy enemy1 = {100, 18, 10, 10, 0};
Enemy enemy2 = {120, 140, 10, 10, 0};
Enemy enemy3 = {140, 127, 10, 10, 0};
Coin coin1 = {120, 75, 5, 5, 1};
Coin coin2 = {120, 20, 5, 5, 1};
Coin coin3 = {120, 130, 5, 5, 1};
Goal goal = {200, 100, 40, 40};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  int deaths = 0;
  int coins = 0;
  
  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {
      case START:
        drawFullScreenImageDMA(start);
        drawString(140, 0, "Use up, down, left, and right arrows", WHITE);
        drawString(150, 0, "to move during gameplay", WHITE);

        state = START_GAME;
        break;

      case START_GAME:
        if (KEY_DOWN(BUTTON_START, currentButtons)) {
          state = PLAY;
        }
        break;
      case PLAY:
        break;
      case WIN:
        break;
    }

    waitForVBlank();

    switch (state) {
      case START:
        break;

      case START_GAME:
        break;

      case PLAY:
        fillScreenDMA(BLUE);
        drawRectDMA(20, 0, 40, 40, GREEN);
        drawRectDMA(goal.y, goal.x, goal.h, goal.w, GREEN);
        drawImageDMA(player.y, player.x, player.h, player.w, square);

        // draw coins
        if (coin1.state) {
          drawRectDMA(coin1.y, coin1.x, coin1.h, coin1.w, YELLOW);
        }
        if (coin2.state) {
          drawRectDMA(coin2.y, coin2.x, coin2.h, coin2.w, YELLOW);
        }
        if (coin3.state) {
          drawRectDMA(coin3.y, coin3.x, coin3.h, coin3.w, YELLOW);
        }

        // draw enemies
        drawRectDMA(enemy1.y, enemy1.x, enemy1.h, enemy1.w, MAGENTA);
        drawRectDMA(enemy2.y, enemy2.x, enemy2.h, enemy2.w, MAGENTA);
        drawRectDMA(enemy3.y, enemy3.x, enemy3.h, enemy3.w, MAGENTA);
        
        //draw labels
        drawString(150, 2, "Coins Collected:", WHITE);
        drawChar(150, 100, coins + 48, WHITE);
        drawString(150, 145, "Death Counter:", WHITE);
        drawChar(150, 230, deaths + 48, WHITE);

        //player movement
        if (KEY_DOWN(BUTTON_DOWN, BUTTONS)) {
          if (player.y < 140) {
            player.y++;
          }
        }
        if (KEY_DOWN(BUTTON_UP, BUTTONS)) {
          if (player.y > 10) {
            player.y--;
          }
        }
        if (KEY_DOWN(BUTTON_LEFT, BUTTONS)) {
          if (player.x > 0) {
            player.x--;
          }
        }
        if (KEY_DOWN(BUTTON_RIGHT, BUTTONS)) {
          if (player.x < 230) {
            player.x++;
          }
        }

        //enemy movement
        if (enemy1.x == 50) {
          enemy1.state = 0;
        } else if (enemy1.x == 220) {
          enemy1.state = 1;
        } 
        if (enemy1.state) {
          enemy1.x -= ENEMY_SPEED;
        } else if (!enemy1.state) {
          enemy1.x += ENEMY_SPEED;
        }

        if (enemy2.y == 10) {
          enemy2.state = 0;
        } else if (enemy2.y == 140) {
          enemy2.state = 1;
        } 
        if (enemy2.state) {
          enemy2.y -= ENEMY_SPEED;
        } else if (!enemy2.state) {
          enemy2.y += ENEMY_SPEED;
        }

        if (enemy3.x == 20) {
          enemy3.state = 0;
        } else if (enemy3.x == 190) {
          enemy3.state = 1;
        } 
        
        if (enemy3.state) {
          enemy3.x -= ENEMY_SPEED;
        } else if (!enemy3.state) {
          enemy3.x += ENEMY_SPEED;
        }

        //quit game
        if (KEY_DOWN(BUTTON_SELECT, BUTTONS)) {
          state = START;
          player.x = 15;
          player.y = 35;
          coins = 0;
          deaths = 0;
          coin1.state = 1;
          coin2.state = 1;
          coin3.state = 1;
        }

        //collision with enemies
        if (((player.x < enemy1.x + enemy1.w) && (player.x + player.w > enemy1.x) && (player.y < enemy1.y + enemy1.h) && (player.h + player.y > enemy1.y)) ||
              ((player.x < enemy2.x + enemy2.w) && (player.x + player.w > enemy2.x) && (player.y < enemy2.y + enemy2.h) && (player.h + player.y > enemy2.y)) ||
              ((player.x < enemy3.x + enemy3.w) && (player.x + player.w > enemy3.x) && (player.y < enemy3.y + enemy3.h) && (player.h + player.y > enemy3.y))) {
          state = PLAY;
          deaths++;
          player.x = 15;
          player.y = 35;
          coins = 0;
          coin1.state = 1;
          coin2.state = 1;
          coin3.state = 1;
        }

        //collision with coins
        if (coin1.state && (player.x < coin1.x + coin1.w) && (player.x + player.w > coin1.x) && (player.y < coin1.y + coin1.h) && (player.h + player.y > coin1.y)) {
          coins++;
          coin1.state = 0;
        }

        if (coin2.state && (player.x < coin2.x + coin2.w) && (player.x + player.w > coin2.x) && (player.y < coin2.y + coin2.h) && (player.h + player.y > coin2.y)) {
          coins++;
          coin2.state = 0;
        }

        if (coin3.state && (player.x < coin3.x + coin3.w) && (player.x + player.w > coin3.x) && (player.y < coin3.y + coin3.h) && (player.h + player.y > coin3.y)) {
          coins++;
          coin3.state = 0;
        }

        //win
        if ((player.x < goal.x + goal.w) && (player.x + player.w > goal.x) && (player.y < goal.y + goal.h) && (player.h + player.y > goal.y)) {
          if (coins == 3) {
            state = WIN;
          }
        }
        break;

      case WIN:
        drawFullScreenImageDMA(win);
        if (KEY_DOWN(BUTTON_SELECT, BUTTONS)) {
          state = START;
          player.x = 15;
          player.y = 35;
          coins = 0;
          deaths = 0;
          coin1.state = 1;
          coin2.state = 1;
          coin3.state = 1;
        }
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
